Lercerss/graphelier

- app/src/components/OrderBookSnapshot.js
- app/src/tests/component-tests/OrderBookSnapshot.test.js
- app/src/tests/utils/mock-data.js
Added OrderBookSnapshot.test.js for testing the behavior of the date and time picker.
- Checks that api call is only made only when date and time are selected. Checks that the api call is only made when the time is committed (when the user lets go of the slider).
- Checks that the state has the proper nanosecond and string values when date or time is selected
> [#26] Added ui tests for date and time picker

- .circleci/config.yml
- .golangci.yml
- README.md
- app/README.md
- core/Dockerfile
- core/README.md
- Modified circleci config to run jobs by component
- Moved README contents
- Added test step for service
Linting for the service is now executed by GolangCI instead of a step in CircleCI. Code styling is still enforced according to `go fmt` standards. I will add it to required checks on PRs.
Failed builds for a component should no longer prevent the build step for other components from executing.
> [#55] Added golangci config

- app/.eslintrc.json
- app/package-lock.json
- app/package.json
- app/src/components/Order.js
- app/src/components/OrderBookSnapshot.js
- app/src/components/template/Dashboard.js
- app/src/utils/date-utils.js
- core/graphelier-service/api/hndlrs/obhandler.go
Added a rule in eslint to enforce the 1-prop-per-line rule.
Also, server was complaining about writing the header after writing the response so I changed the ordering on the backend.
Most important part of this PR is the `handleCommitTime` method in OrderBookSnapshot.js and the `convertNanosecondsToUTC` in date-utils.js.
> [#65] Timestamp gets converted to UTC

- .circleci/config.yml
- core/graphelier-service/api/hndlrs/handlers.go
- core/graphelier-service/api/hndlrs/msghandler.go
- core/graphelier-service/api/hndlrs/msghandler_test.go
- core/graphelier-service/api/hndlrs/obhandler.go
- core/graphelier-service/api/routes.go
- core/graphelier-service/db/mongo.go
- core/graphelier-service/models/messages.go
- core/graphelier-service/models/paginator.go
- Backend now serves messages using sod_offset field
- Connector was changed to be an interface to allow for testing
- Handler now writes header before encoding json object because
it was giving warnings before
> [#51] Serving messages with pagination

- core/scripts/importer.py
- core/scripts/lobster/extender.py
- core/scripts/lobster/parser.py
- core/scripts/models/message.py
- core/scripts/models/order_book.py
- core/scripts/mongo_db/db_utils.py
- core/scripts/pylintrc
- core/scripts/tests/test_extender.py
- core/scripts/tests/test_orderbook.py
- If message would lead to a price movement, drop all orders that would conflict with it first
- Prices are changed according to the top of book before the extended sample is started
- Added dependency on the `orderbook` file from Lobster, data can also be passed through the new `--top-of-book` argument to avoid downloading the file
> [#81] Adjust price on extended samples

- core/scripts/importer.py
Crash caused by uninitialized var in scope
> [#81, #90] Fixed crash when providing `-t`

- core/graphelier-service/api/hndlrs/handlers.go
`log.Fatal` leads to a call to `os.Exit(1)`, `Print` instead
> [#98] Prevent exit on error in service

- core/scripts/importer.py
- core/scripts/lobster/extender.py
- core/scripts/lobster/parser.py
- Importer previously lost precision when storing to the db because it
was storing floats for the timestamp field. Now it will store ints.
> [#95] Converted timestamp to int to keep precision

- core/graphelier-service/api/hndlrs/insthandler.go
- core/graphelier-service/api/hndlrs/insthandler_test.go
- core/graphelier-service/api/hndlrs/msghandler_test.go
- core/graphelier-service/api/hndlrs/obhandler_test.go
- core/graphelier-service/api/routes.go
- core/graphelier-service/db/mongo.go
Serve available instruments to let app know which values are valid
Route spec:
path: `/instruments/`
response format: `["SPY","AAPL","MSFT"]`, a json list of strings
> [#113] Instruments route

- core/graphelier-service/models/orderbooks.go
Allows orderbook to save the new sod_offset even if there is no delta
> [#117] Always send message to orderbook

- core/graphelier-service/api/hndlrs/insthandler_test.go
- core/graphelier-service/api/hndlrs/msghandler_test.go
- core/graphelier-service/api/hndlrs/obhandler.go
- core/graphelier-service/api/hndlrs/obhandler_test.go
- core/graphelier-service/api/routes.go
- core/graphelier-service/db/mongo.go
- core/graphelier-service/models/orderbooks.go
- core/scripts/importer.py
- core/scripts/lobster/parser.py
- core/scripts/mongo_db/db_connector.py
- Importer script maintains value per instrument
- Service reads and caches meta values on startup
- This can also be refreshed by a GET to `/_refresh/`
- Default interval value in the script has been reduced to 0.1s from 10s
- Unified response format for `/orderbook/`, timestamps out of bounds return an empty orderbook
To allow migration of existing dataset, simply:
```
db.createCollection("meta")
db.meta.insertOne({instrument: "SPY", interval: NumberLong("10000000000")})
db.orderbook.insertOne({instrument: "SPY", bids: [], asks: [], timestamp: NumberLong("0"), last_sod_offset: NumberLong("0")})
```
> [#94, #128] Store interval value in meta collection

- app/src/components/MultiDirectionalScroll.tsx
Fixed for all usages of `MultiDirectionalScroll`.
> [#146] Fixed crash on earliest time being selected

- core/graphelier-service/api/hndlrs/handlers.go
- core/graphelier-service/api/hndlrs/insthandler.go
- core/graphelier-service/api/hndlrs/msghandler.go
- core/graphelier-service/api/hndlrs/obhandler.go
- core/graphelier-service/db/mongo.go
- core/graphelier-service/main.go
- core/graphelier-service/utils/utils.go
Using https://github.com/sirupsen/logrus as a logger due to its ease of use and similar API to built-in `log` module.
Added logs to different handlers based on behavior. Also added logs to mongo calls to record performance.
Log format looks like this:
```
[TRACE]: 2020-01-20T23:58:49Z - mongo/RefreshCache took 497.982µs
```
> [#134] Verbose logging with log levels for service

- app/src/components/MessageList.tsx
- app/src/components/MultiDirectionalScroll.tsx
- app/src/components/OrderBookSnapshot.tsx
- app/src/components/TimestampOrderBookScroller.tsx
- app/src/constants/Constants.ts
- app/src/styles/MessageList.ts
- app/src/tests/component-tests/MessageList.test.tsx
- app/src/tests/component-tests/TimestampOrderBookScroller.test.tsx
#132
Recentering to the selected message now works after all intuitive manipulations of the visible orderbook
- New message selected
- Traversing messages with the **Forward** and **Backward** arrows
- selecting a new date and time
- Manually via the Tilde `
Issue
- Cannot determine properly to recenter when message selected within < 5 of an edge and **not** recenter when it is simply continuous scrolling from top or bottom.
> [#132] Kontrolol/132/return to recent message

- core/scripts/mongo_db/db_utils.py
Small python ints are automatically stored as int32, force conversion into int64 to match service expectations.
> [#164] Force interval_multiple to be an int64

- app/package.json
- app/src/components/OrderBookSnapshot.tsx
Fixed issue where X-axis is truncated on the left when the window is resized, and no longer shows 9:30 AM.
Changes:
- Added call to `updateGraphData` when window is resized
- Number of data points requested now depends on window width rather than screen width
> [#172] Fixed issue with X-axis on window resize

- app/src/components/TopOfBookGraph.tsx
Zooming out once zoomed in too deep is now unblocked.
> [#191] Fixed zoom out bug when zoomed in too deep

- app/src/utils/date-utils.ts
1. Created date object based on backend timestamp.
2. Gets timezone offset of that timestamp wrt UTC.
3. Adds difference with hardcoded agreed upon timezone (EDT).
> [#170] resolved bug in timezone handler for scale

- app/src/tests/samples/socket_client.js
- core/graphelier-service/api/hndlrs/playbackhandler.go
- core/graphelier-service/api/hndlrs/playbackhandler_test.go
- core/graphelier-service/api/routes.go
- core/graphelier-service/models/orderbooks.go
Changed request parameter from start timestamp to sod_offset. This will prevent sending duplicate modifications in the first batch when there are multiple messages for the initial timestamp.
> [#218] Set correct timestamp for playback

- app/src/components/ArticleDetails.tsx
- app/src/components/ArticleItem.tsx
- app/src/components/NewsTimeline.tsx
Fixed bug where all instruments in the article details were colored and clickable.
The article details modal now displays non-orderbook instruments as grey, non-clickable boxes.
> [#228] Fixed bug with clickable, colored tickers in the article details

- app/src/components/OrderBookSnapshot.tsx
- app/src/components/PlaybackControl.tsx
- core/graphelier-service/api/hndlrs/playbackhandler.go
- Rate cannot be lower or equal to 0
- Use ceil instead of floor in frontend for message rate
> [#230] Add rate validation in backend
