Lercerss/graphelier

app/src/components/Order.js, app/src/components/PriceLevel.js, app/src/components/TimestampOrderBookScroller.js, app/src/styles/Order.js, app/src/styles/OrderBookSnapshot.js, app/src/styles/PriceLevel.js
This following is a sample of the implementation:
- For small quantities, a tooltip is used to show the quantity
=> [#29] Relative box sizes for quantities

app/src/components/OrderBookSnapshot.js, app/src/components/TimestampOrderBookScroller.js
=> [#59] removed inefficient slider callbacks/setStates

app/src/App.js, app/src/components/OrderBookSnapshot.js, app/src/components/TimestampOrderBookScroller.js, app/src/styles/App.js, app/src/styles/OrderBookSnapshot.js, app/src/styles/TimestampOrderBookScroller.js
Added more styling to the time Slider and the TimeStampOrderBookScroller Card:
=> [#40] Added more styling to the Slider and the Card

core/db/db_setup.js, core/scripts/importer.py, core/scripts/models/message.py, core/scripts/models/order_book.py, core/scripts/mongo_db/db_utils.py
- sod_offset added in messages collection
- last_sod_offset added in orderbooks collection
This is needed to add uniqueness to messages
=> [#76] SOD offset now saved in DB

core/db/db_setup.js, core/graphelier-service/models/messages.go, core/graphelier-service/models/orderbooks.go, core/scripts/importer.py
- last_sod_offset now returned to the frontend when requesting the orderbook
- index created to optimize sorting of messages by sod_offset
=> [#76] SOD offset now includes the dates timestamp

app/.env, app/package.json
Added `.env` file for running ESLint
=> [#87] Fixed support for running app in windows with eslint

core/graphelier-service/api/hndlrs/msghandler_test.go, core/graphelier-service/models/messages.go, core/graphelier-service/models/orderbooks.go, core/graphelier-service/models/orderbooks_test.go
- Wrote test cases for orderbook building
=> [#41][#89] Fixed bug causing pricelevel duplicates

core/scripts/importer.py
Set initial values on the orderbook before sending messages
=> [#97] Default values for initial orderbook snap

core/graphelier-service/models/orderbooks.go, core/graphelier-service/models/orderbooks_test.go
- fixes bug that incremented last_sod_offset by 2 when moving forward in a message
=> [#35] increment bug fix

app/.eslintrc.json, app/src/components/OrderBookSnapshot.js, app/src/tests/component-tests/OrderBookSnapshot.test.js, app/src/tests/utils/mock-data.js, app/src/utils/date-utils.js, core/graphelier-service/models/messages.go, core/graphelier-service/models/orderbooks.go, core/graphelier-service/models/paginator.go
- This is needed to keep the number's precision on the frontend
=> [#95] Big numbers are now converted to strings

app/package-lock.json, app/src/components/Order.js, app/src/styles/MessageList.js, app/src/styles/OrderBookSnapshot.js, app/src/styles/TimestampOrderBookScroller.js, app/src/utils/order-book-utils.js
=> Scale application display size #105

app/src/components/MessageList.js, app/src/utils/date-utils.js, app/src/utils/order-book-utils.js
- Fixed null on deep comparison of list items
- Set timezone conversions to use EDT
- Fixed wrong timestamp (UDT date) being displayed on message list
=> [#118] Fixed timezone discrepancy

core/scripts/importer.py, core/scripts/lobster/extender.py, core/scripts/tests/test_extender.py
- Set timezone so that it doesnt change with daylight savings
=> [#118] Timezone set to NASDAQ's

README.md, app/Dockerfile, app/nginx/nginx.conf, core/Dockerfile, docker-compose.override.yml, docker-compose.yml
Set up a basic nginx server to serve the react application
=> Set up prod for frontend #107

.circleci/config.yml
Set up ECS and ECR on AWS. On merge, new docker images will be created and deployed.
NOTE:
This might not work I might need to open another PR.
=> [#109] Set up CD pipeline to deploy on ECS

.circleci/config.yml, app/package.json, app/src/constants/Constants.js, core/Dockerfile, docker-compose.override.yml, docker-compose.yml
- Fixed the deploy job ordering
- Prod environment now points to the correct host
=> [#109] Fixed URL issues

README.md, docker-compose.prod.yml, docker-compose.yml
- Running the dev environment now only exposes port 3000
=> [#144] Fixed multiple ports being exposed

.circleci/config.yml
- AWS ECS will now correctly identify the newly pushed images
=> [#109] Fixed incorrectly named images in CI config

README.md, app/src/constants/Constants.ts
- Frontend now uses elastic-ip for the backend
requests
=> [#148] Changed frontend to use elastic IP

.circleci/config.yml, core/.gitignore
Reports generated using `jest` for app, `go tool cover` for service and `coverage` for scripts.
=> [#134] Coverage reports for all components

app/src/App.tsx, app/src/components/CustomLoader.tsx, app/src/components/GreetingsLoader.tsx, app/src/components/MessageList.tsx, app/src/components/OrderBookSnapshot.tsx, app/src/components/TimestampOrderBookScroller.tsx, app/src/constants/Constants.ts, app/src/styles/App.ts, app/src/styles/CustomLoader.ts, app/src/styles/MessageList.ts, app/src/styles/OrderBookSnapshot.ts, app/src/styles/TimestampOrderBookScroller.ts, app/src/styles/index.css, app/src/tests/component-tests/MessageList.test.tsx, app/src/tests/component-tests/OrderBookSnapshot.test.tsx, app/src/tests/component-tests/TimestampOrderBookScroller.test.tsx
#123
- Added Greetings for loading App for the first time
- Added UI Feedback to show that data is loading
Issue
- Can not use desirable components for showing data being loaded because the entire UI freezes when performing the **Top of the Book** Logic, causing the circling or moving effects to also freeze.
=> [#123] Kontrolol/loading

app/src/App.tsx, app/src/components/GreetingsLoader.tsx, app/src/styles/CustomLoader.ts
Instead of using time and checkling seconds every so often with interval, using callbacks and two single timeoutcalls.
=> #123 Cleaned Code, improved performance.

app/package-lock.json, app/package.json, app/src/actions/actions.ts, app/src/actions/types.ts, app/src/components/Order.tsx, app/src/components/OrderBookSnapshot.tsx, app/src/components/OrderInformation.tsx, app/src/components/PriceLevel.tsx, app/src/components/TimestampOrderBookScroller.tsx, app/src/constants/Constants.ts, app/src/models/OrderBook.ts, app/src/reducers/generalReducers.ts, app/src/services/OrderBookService.ts, app/src/store/index.ts, app/src/styles/Order.ts, app/src/styles/OrderBookSnapshot.ts, app/src/styles/OrderInformation.ts, app/src/tests/component-tests/OrderBookSnapshot.test.tsx, app/src/tests/component-tests/OrderInformation.test.tsx, app/src/tests/component-tests/TimestampOrderBookScroller.test.tsx, app/src/tests/utils/mock-data.ts, package-lock.json
Issue #126 
This is demo of what the order information looks like
Things left to do that require redux:
1. Change colour of order component when clicked on
2. Change state of orderbook when messages are clicked on
=> Order information component #126

core/graphelier-service/db/mongo.go, core/graphelier-service/models/orderbooks.go, core/graphelier-service/models/orderbooks_test.go
- Removed assumption that orders are sorted by id within a price level
- Added test case to document
=> [#190] Fixed incorrect data in Top of Book graph

.circleci/config.yml, .gitignore, core/.gitignore, docker-compose.yml, news/.gitignore, news/db/Dockerfile, news/service/Dockerfile, news/service/requirements.txt
- Set up basic docker files for the graphelier-news service
- Updated CI to include the new images
=> [#197] Set up docker for the news API

.circleci/config.yml, core/graphelier-service/db/mongo.go, news/scripts/Dockerfile, news/scripts/pylintrc, news/scripts/requirements.txt, news/scripts/summarizer.py, news/scripts/summarizer.spec.py, news/service/Dockerfile
- Using NLTK, the summarizer takes in a string,
and summarizes it to however many number of sentences
Example article:
https://globalnews.ca/news/6649164/canada-coronavirus-cases/, 6 sentences
Output:
These are both presumptive positive samples, but are yet to be officially confirmed. So far, cases have only been confirmed in Ontario, B.C., Quebec and Alberta. The first official case of COVID-19 reported in Canada was confirmed on Jan. 25, when a man in his 50s arrived in Toronto from Wuhan, China, the crux of the new coronavirus outbreak. Health Canada has active travel health notices posted for seven regions at the moment: China, Hong Kong, Iran, Japan, Northern Italy, Singapore and South Korea. The new coronavirus was first identified in Hubei province, China, in December 2019 and …
=> [#199] Implement a text summarizer

news/service/Dockerfile, news/service/main.py, news/service/requirements.txt
basic flask server connected to mongodb and has some sample routes
=> [#201] basic flask server for news api

core/graphelier-service/models/playback.go
Frontend needs this extra attribute to know what order is affected by a modification.
=> [#206] Add direction attribute to modifications

app/package-lock.json, app/src/actions/actions.ts, app/src/actions/types.ts, app/src/components/OrderBookSnapshot.tsx, app/src/components/OrderInformation.tsx, app/src/models/OrderBook.ts, app/src/reducers/generalReducers.ts, app/src/styles/App.ts, app/src/styles/OrderInformation.ts, app/src/tests/component-tests/OrderBookSnapshot.test.tsx
=> #188 Clicking on message in Order Details

core/graphelier-service/api/hndlrs/playbackhandler.go, core/graphelier-service/models/orderbooks.go, core/graphelier-service/models/playback.go
- Added last_sod_offset to playback response
- Fixed rateRealtime usage, mult. instead of div. of delay
=> [#178] Added last_sod_offset to playback response

news/service/Dockerfile, news/service/server.py
=> [#201] Fix for exposed port on prod for graphelier news

news/service/requirements.txt, news/service/server.py
Ran flask application with a CORS decorator
=> [#201] Decorated news api with CORS support
